### PR TITLE
Add suport for pytest-xdist

### LINKED ISSUE #64: Doesn't work with pytest-xdist
I'm getting:
```
[gw54] linux2 Python 2.7.10 cwd: /home/omer/Documents/Projects/zBackend/devices/malware/tests/functional
gw53 C / gw54 CINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/omer/Documents/Projects/zBackend/.tox/py27-malware-functional/lib/python2.7/site-packages/_pytest/main.py", line 80, in wrap_session
INTERNALERROR>     config.do_configure()
INTERNALERROR>   File "/home/omer/Documents/Projects/zBackend/.tox/py27-malware-functional/lib/python2.7/site-packages/_pytest/config.py", line 618, in do_configure
INTERNALERROR>     self.hook.pytest_configure(config=self)
INTERNALERROR>   File "/home/omer/Documents/Projects/zBackend/.tox/py27-malware-functional/lib/python2.7/site-packages/_pytest/core.py", line 521, in __call__
INTERNALERROR>     return self._docall(self.methods, kwargs)
INTERNALERROR>   File "/home/omer/Documents/Projects/zBackend/.tox/py27-malware-functional/lib/python2.7/site-packages/_pytest/core.py", line 528, in _docall
INTERNALERROR>     firstresult=self.firstresult).execute()
INTERNALERROR>   File "/home/omer/Documents/Projects/zBackend/.tox/py27-malware-functional/lib/python2.7/site-packages/_pytest/core.py", line 394, in execute
INTERNALERROR>     res = method(*args)
INTERNALERROR>   File "/home/omer/Documents/Projects/zBackend/.tox/py27-malware-functional/lib/python2.7/site-packages/pytest_sugar.py", line 122, in pytest_configure
INTERNALERROR>     sugar_reporter = SugarTerminalReporter(standard_reporter)
INTERNALERROR>   File "/home/omer/Documents/Projects/zBackend/.tox/py27-malware-functional/lib/python2.7/site-packages/pytest_sugar.py", line 148, in __init__
INTERNALERROR>     TerminalReporter.__init__(self, reporter.config)
INTERNALERROR> AttributeError: 'NoneType' object has no attribute 'config'
[gw53] node down: Not properly terminated
```
I'd rather have a responsive CI than a pretty looking log output but if possible I'd like to have both.
Any idea what's broken here?

### PR DESCRIPTION
**Pull request by thedrow**
This fixes #64 .

### CODE REVIEW

**Comment by Frozenball** [comment]
Thanks, I'll take a look later.

**Comment by thedrow** [comment]
@Frozenball We probably need have the build install different plugins to ensure nothing breaks.

**Comment by thedrow** [comment]
Now I'm getting a different error:
```
INTERNALERROR>     terminal_reporter.tests_count += len(items)
INTERNALERROR> AttributeError: 'NoneType' object has no attribute 'tests_count'
scheduling tests via LoadScheduling
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/omer/.virtualenvs/zBackend/lib/python2.7/site-packages/_pytest/main.py", line 84, in wrap_session
INTERNALERROR>     doit(config, session)
INTERNALERROR>   File "/home/omer/.virtualenvs/zBackend/lib/python2.7/site-packages/_pytest/main.py", line 122, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/omer/.virtualenvs/zBackend/lib/python2.7/site-packages/_pytest/core.py", line 521, in __call__
INTERNALERROR>     return self._docall(self.methods, kwargs)
INTERNALERROR>   File "/home/omer/.virtualenvs/zBackend/lib/python2.7/site-packages/_pytest/core.py", line 528, in _docall
INTERNALERROR>     firstresult=self.firstresult).execute()
INTERNALERROR>   File "/home/omer/.virtualenvs/zBackend/lib/python2.7/site-packages/_pytest/core.py", line 394, in execute
INTERNALERROR>     res = method(*args)
INTERNALERROR>   File "/home/omer/.virtualenvs/zBackend/lib/python2.7/site-packages/xdist/dsession.py", line 514, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/home/omer/.virtualenvs/zBackend/lib/python2.7/site-packages/xdist/dsession.py", line 532, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/home/omer/.virtualenvs/zBackend/lib/python2.7/site-packages/xdist/dsession.py", line 570, in slave_slavefinished
INTERNALERROR>     assert not crashitem, (crashitem, node)
INTERNALERROR> AssertionError: ('devices/malware/tests/unit/test_features_serializer.py::describe_features_serializer::describe_serialization::it_should_not_return_an_object_id_attribute_in_the_serialization_result', <SlaveController gw3>)
```

**Comment by thedrow** [comment]
@Frozenball Any idea?

**Comment by thedrow** [comment]
@Frozenball Ok so now pytest-sugar doesn't crash when xdist is used but it still doesn't add the new terminal reporter.

**Comment by codingjoe** [comment]
:+1:

**Comment by thedrow** [comment]
@codingjoe Any idea how to make the progress bar work?
I can't seem to get the number of tests that are going to be run with xdist installed.

**Comment by aadis** [comment]
I'd want this.

**Comment by thedrow** [comment]
@aadis help in getting the progress bar to work will be much appreciated.

**Comment by thedrow** [comment]
@Frozenball can you help me resolve this?

**Comment by RonnyPfannschmidt** [comment]
the progress bard needs help from the xdist side, get at me on freenode

**Comment by thedrow** [comment]
@RonnyPfannschmidt Got it, will do.

**Comment by AbdealiJK** [comment]
Was wondering if there was any update on this feature - would love to have it

**Comment by thedrow** [comment]
I just need to commit the changes I made and this is ready for merge.

**Comment by thedrow** [comment]
I have no idea why the CI isn't running. Hold on.

**Comment by thedrow** [comment]
I rewrote the build process to test with supported and unsupported versions of xdist and added 3.5 to the matrix among other things.
The tests are now run in CI using tox like they should.

**Comment by thedrow** [comment]
Seems like pytest 2.6 doesn't support python 3.5. I removed that combination from the build matrix.

**Comment by thedrow** [comment]
Everything seems to be in order.
@Frozenball Please merge.

**Comment by thedrow** [comment]
Any chance to get this merged?

**Comment by or** [comment]
Hola. Apologies for the inactivity. I'll try to look at this tonight. I think xdist support would be great. :)

**Comment by thedrow** [comment]
Thanks. It's done, working and passing tests.

**Comment by Frozenball** [comment]
My apologies for being so inactive with this project. I can publish a new version on PyPi after @or code reviews

**Comment by or** [comment]
Cheers, @thedrow. I tried it and it worked very well. Also well done on the extensive travis reconfiguration.

I merged it, @Frozenball, but you better look over the travis stuff sometime.

**Comment by thedrow** [comment]
Thanks guys. Please release this as soon as possible.

**Comment by AbdealiJK** [comment]
Awesome !
Thanks :)

**Comment by Frozenball** [comment]
0.6.0 released

**Pull request merged**
