### PR TITLE
Separate test class and method name with double colon too

### LINKED ISSUE #150: Failed tests name contains `.` instead of `::` in verbose mode
When a test fails and pytest is run in verbose mode, the failed test name contains `.` instead of `::` which doesn't match the name expected by pytest itself to run the test.

e.g. the following code:

```python
import pytest


class TestFails:

    def test_fail1(self):
        assert True is False

    @pytest.mark.parametrize('foo,bar', [(1, 3), (2, 4)])
    def test_fail2(self, foo, bar):
        assert False is True
```

causes the following output:

```
$ pytest -v test_foo.py
Test session starts (platform: linux, Python 3.6.5, pytest 3.8.0, pytest-sugar 0.9.1)
cachedir: .pytest_cache
rootdir: /home/ack/Desktop, inifile:
plugins: xdist-1.23.0, sugar-0.9.1, postgresql-1.3.4, mock-1.10.0, forked-0.2, cov-2.6.0


―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― TestFails.test_fail1 ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

self = <test_foo.TestFails object at 0x7f9351761fd0>

    def test_fail1(self):
>       assert True is False
E       assert True is False

test_foo.py:7: AssertionError

 test_foo.py::TestFails.test_fail1 ⨯                                                                                                                                                                                                                                                                                                                                                                                        33% ███▍      

――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― TestFails.test_fail2[1-3] ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

self = <test_foo.TestFails object at 0x7f9356ee2748>, foo = 1, bar = 3

    @pytest.mark.parametrize('foo,bar', [(1, 3), (2, 4)])
    def test_fail2(self, foo, bar):
>       assert False is True
E       assert False is True

test_foo.py:11: AssertionError

 test_foo.py::TestFails.test_fail2[1-3] ⨯                                                                                                                                                                                                                                                                                                                                                                                   67% ██████▋   

――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― TestFails.test_fail2[2-4] ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

self = <test_foo.TestFails object at 0x7f9356eef2b0>, foo = 2, bar = 4

    @pytest.mark.parametrize('foo,bar', [(1, 3), (2, 4)])
    def test_fail2(self, foo, bar):
>       assert False is True
E       assert False is True

test_foo.py:11: AssertionError

 test_foo.py::TestFails.test_fail2[2-4] ⨯                                                                                                                                                                                                                                                                                                                                                                                  100% ██████████

Results (0.07s):
       3 failed
         - test_foo.py:6 TestFails.test_fail1
         - test_foo.py:9 TestFails.test_fail2[1-3]
         - test_foo.py:9 TestFails.test_fail2[2-4]

```

### PR DESCRIPTION
**Pull request by albertodonato**
Fixes #150

### CODE REVIEW

**Comment by albertodonato** [comment]
I'm not sure why one test is failing, but I see the same failure in master (it seems line number it test output is different)

**Comment by Frozenball** [comment]
I'll release a version a bit later after I have made sure nothing breaks. CI builds tend to fetch latest pytest-sugar so one bad release can break tons of builds.

**Comment by Frozenball** [comment]
Oops, this was not a good idea.

````
$ pytest faketests/

 faketests/animals/test_xpass_and_xfail::py ⨯                                                                                  6% ▋
 faketests/fruits/test_lots_of_successful_tests::py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓ 19% █▉
                                                   ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
````

**Comment by albertodonato** [comment]
My bad, I didn't realize the `test_name` would end up containing the filename when verbose is not used.
Should be fixed by #154

**Pull request merged**
