### PR TITLE
pytest_collection_modifyitems: fix counting items

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/Frozenball/pytest-sugar/issues/143

I could imagine this also fixes https://github.com/Frozenball/pytest-sugar/issues/142.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
looks good, could use an elaborate test

**Comment by blueyed** [comment]
Does not seem to work via conftest in the test?!
(it worked with my custom plugin though - does it require a plugin in the test, too?)
Is there a better way in general, e.g. using another hook instead?

**Comment by blueyed** [comment]
Changed it to use `pytest_runtestloop`.

**Comment by blueyed** [comment]
@RonnyPfannschmidt 
Does this make sense?

**Comment by Frozenball** [comment]
This is quite magic for me but 💁‍♂️

**Pull request merged**
