### PR TITLE
Remove support for windows #46 - Gibberish stdout in windows

### PR DESCRIPTION
**Pull request by manojpkr**
Remove support for windows #46

### CODE REVIEW

**Comment by Dog** [comment]
I am currently running this in Windows 7 under GitBash with ConEmu. The progress bar is not displaying for me properly. I can debug further if there is something else you'd like me to try.

**Comment by wwwald** [comment]
The gibberish appears because the Windows console used codepage 850 by default (MS-DOS Latin 1). Changing this to codepage 65001 = UTF-8 fixes the gibberish.

```chcp 65001```

Mind you: the actual characters that appear also depend on the console font that is used, and the console environment. With font Lucida console and the alternative ["cmder" console](https://github.com/cmderdev/cmder), I see pretty decent py.test output:
image

**Comment by Natim** [comment]
Then we should probably add this in the troubleshooting part of the documentation.

**Comment by Frozenball** [comment]
Let's add this to documentation

**Comment by cb109** [comment]
Just to elaborate on this for other Windows users: I am using the [git bash](https://git-for-windows.github.io/) on Windows together with [ConEmu](https://conemu.github.io/) and had struggles to make this work.

Setting the codepage in a git bash will only work with a [small change](http://stackoverflow.com/questions/23213484/how-to-change-console-code-to-1252):
`$ chcp.com 65001`

This however will be recognized as `cp65001` by python instead of the correct `65001` (at least on Python 2.7x), it [seems to be a bug](http://stackoverflow.com/questions/878972/windows-cmd-encoding-change-causes-python-crash). We can map that to the correct codec though. Inside my top-level `conftest.py` I was able to produce decent output with the following adjustments:
```python

import codecs
codecs.register(lambda name: codecs.lookup('utf-8') 
                if name == 'cp65001' else None)

import colorama
colorama.init()
```
Some special characters still seem to not be recognized, but at least the progress bars look ok.

**Comment by MaximilianR** [comment]
FYI I have this problem when running tests inside a docker container. Container is running ubuntu 16, local is macOS.

**Comment by Frozenball** [comment]
Are we sure it's pytest-sugar issue and not a problem in Docker etc.?

**Comment by MaximilianR** [comment]
Thanks for responding @Frozenball. 

It's definitely coincident with pytest-sugar - it was fine before, the gibberish when pytest-sugar was installed, then fine when reverted...

But it might be because Docker can't display complex stdout, or something else that's unavoidable. I'm less familiar with the mechanics there

**Comment by anntzer** [comment]
For slightly better Windows support, you may want to consider switching the dependency from termcolor to colorama, which should provide the same features, but, as mentioned in https://github.com/Teemu/pytest-sugar/pull/49#issuecomment-270347640, can additionally preprocess ANSI color codes on Windows (see e.g. Description at https://pypi.org/project/colorama/).

**Pull request closed without merging**
